### ISSUE TITLE
'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by Piyushjoshi007** [krishnavelu/alice_blue#275]
when I am trying to place an order from the default code provided by you, I am getting the above error, please check.

below is the code:

```
 print(
                     alice.place_order(transaction_type = TransactionType.Buy,
                     instrument = alice.get_instrument_by_symbol('NSE', 'INFY'),
                     quantity = 1,
                     order_type = OrderType.Market,
                     product_type = ProductType.Intraday,
                     price = 0.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False)
)
```

error is in this line :  'order_type': order_type.value,

`AttributeError: 'str' object has no attribute 'value'`

**Comment by Piyushjoshi007** [comment]
?

**Comment by krishnavelu** [comment]
I don’t get this error. Try to run only example code as it is. Don’t add any extra stuffs. Also update to latest python.

**Comment by Piyushjoshi007** [comment]
Hi thanks for the support, lower version of python was the problem, after updating it to 3.8, the problem got solved, you can close this issue now.

**Comment by krishnavelu** [comment]
Why 3.8? 3.9.4 is out.

**Comment by Piyushjoshi007** [comment]
Anaconda is to be blamed here, it currently supports python only till 3.8.
